name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          output_file: cppcheck.txt
          other_options: "--error-exitcode=1"

      - name: print-result
        run: cat cppcheck.txt
